### ISSUE TITLE
Replace netsim_embed::run by netsim_embed::init (breaking change)

### ISSUE THREAD

**Issue by Ekleog** [ipfs-rust/netsim-embed#5]
Hey!

A thought I had while integrating netsim-embed with my tests was, `namespace::unshare_user` needs to be run before any thread is created.

In turn, this means that one has to not use the default test harness. That's not that big a problem, `libtest-mimic` is there to make that easy.

However, there is one thing that bothers me: I had to not use `netsim_embed::run` both because it initialized env_logger (which works only once per process, so it couldn't run twice even in sequence), and because it runs namespace::unshare_user, which would mean that I couldn't run my tests in multiple threads.

So the way I'm doing things is now:
```rust
netsim_embed_machine::namespace::unshare_user().unwrap();
tracing_subscriber::fmt::init().unwrap();
// ...
// in each test thread
futures::executor::block_on( [here the thing I'd have put in netsim_embed::run] )
```

Overall, this makes me think that the API of `netsim_embed::run` ought to be re-thought. An idea I had was:
1. Add `netsim_embed::init` that runs unshare_user and then sets a global AtomicBool
2. Have `netsim_embed::run` neither initialize env_logger nor run unshare_user, but just assert that the AtomicBool is set and then runs the future

What would you think about such a change? Sure it's a breaking change, so it'd require releasing a 0.2, but I'd guess netsim_embed is mostly used for tests anyway, which means that releasing breaking changes shouldn't result in too much churn for the ecosystem, as tests could just stay on the old version?

**Comment by dvc94ch** [comment]
the run function is a small utility involving 3 loc. The way you're doing it is the way to do it if you require the extra flexibility. I'd suggest leaving it as it is.

**Comment by Ekleog** [comment]
While I understand your point, I'm a bit worried that from current documentation it looks like `run` should be the main entry point, and the fact it's very restricted in usage (basically, it can only be used as top-level in `main`) makes it a trap point for downstream users: even just calling it twice one after the other would fail, so most often it isn't useful.

Hence my thinking that it maybe should be removed altogether, or at least strongly documented with something like:
> This should only ever be used once in `main`, and will initialize env_logger and thus make customization impossible. If you want to use it in more complex scenarios, please use
> ```
> // once per complete program execution (so at the top of main):
> netsim_embed_machine::namespace::unshare_user().unwrap();
> tracing_subscriber::fmt::init().unwrap(); // or env_logger::init()
> // then on each use of netsim_embed:
> futures::executor::block_on( [here the thing I'd have put in netsim_embed::run] )
> ```

(Also, it might make sense to re-export `netsim_embed_machine::namespace::unshare_user` from `netsim_embed` to make the alternative more seamless)

What do you think? :)

**Comment by dvc94ch** [comment]
Sounds good to me, would you like to open a PR for it?
