### ISSUE TITLE
library level logger init conflicts with library user's instance of logger init.

### ISSUE THREAD

**Issue by sjmackenzie** [ipfs-rust/netsim-embed#7]
https://github.com/ipfs-rust/netsim-embed/blob/d7bf7a9c1c9d3807bc361622e0b5384d5857fc83/src/lib.rs#L20

Typically the library user will init their own, sometimes highly configured logger, the library shouldn't do it as it results in a conflict.

**Comment by dvc94ch** [comment]
This has been discussed before. You're welcome to use a different `run` method. See https://github.com/ipfs-rust/netsim-embed/issues/5

**Comment by dvc94ch** [comment]
I guess if you open a PR we can remove it.

**Comment by sjmackenzie** [comment]
Closing in favour of how you designed it to be used in #5
